### ISSUE TITLE
Durante a execução do XC Server é necessário manter um histórico de logs de uma forma que seja possível observar processamentos de um ou mais dias

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/prodtools#1]
### Descrição da tarefa

É esperado que os logs em formato de arquivo possuam um tamanho maior do que `10kb` como é feito atualmente e também é esperado que a rotação de logs seja realizada de uma forma previsível.

Observando o código a baixo é possível identificar o tamanho máximo do arquivo de log em `10240`, é desejável que essa limitação seja muito superior uma vez que o programa XC server emite uma quantidade de informações muito considerável durante a sua execução. Se possível também é desejável que a quantidade de backups seja aumentada para um número viável.

https://github.com/scieloorg/PC-Programs/blob/56b452a882ebf696dc69cdbd5c761be46f134016/src/scielo/bin/xml/prodtools/utils/logging_config.py#L20-L26

Também pode ser interessante observar outras estratégias para rotação do log como https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler que nos traz previsibilidade na separação de logs por dia, hora, minuto e etc.

### Subtarefas

- [ ] Avaliar uma nova estratégia para armazenamento de logs
- [ ] Escrever a proposta de implementação e viabilidade SE uma nova estratégia for definida
- [ ] Aumentar o limite em bytes que um arquivo de log pode armazenar

## Considerações e notas

N/A

**Comment by robertatakenaka** [comment]
https://medium.com/@rahulraghu94/overriding-pythons-timedrotatingfilehandler-to-compress-your-log-files-iot-c766a4ace240

**Comment by joffilyfe** [comment]
>     * https://medium.com/@rahulraghu94/overriding-pythons-timedrotatingfilehandler-to-compress-your-log-files-iot-c766a4ace240
> 
>     * https://python.hotexamples.com/pt/examples/logging.handlers/TimedRotatingFileHandler/-/python-timedrotatingfilehandler-class-examples.html
> 
>     * https://stackoverflow.com/questions/46021721/python-timedrotatingfilehandler-with-dictconfig

Ótimos links. 

---

Acho que essa sugestão de usar o `timedrotatingfilehandler` não é uma boa para o estado atual do XC. Explico: pelo que pude ler da documentação, a rotação do log só acontece quando o `gatilho` para rotacionar é disparado enquanto o processo está rodando. Exemplo:

Se eu tenho um processo longo, que por exemplo dura duas horas e configurei o `when: "m"` então o log será rotacionado pelo menos `120 vezes`. Utilizando o mesmo exemplo mas com um `when: "h"` o log seria rotacionado `até 2 vezes` (a rotação acontece de acordo com o relógio do servidor que executa o processo).

Porém, se pegarmos o mesmo exemplo acima com `when: "h"` mas com um processo que dura `5 minutos` (tipo o xc) o log não seria rotacionado a menos que ele iniciasse por exemplo entre 00:58 e finalizasse às 01:03 (o gatilho para rotação aconteceria às 01:00).

Acho que faz sentido para a aplicação atual manter a estratégia utilizada atualmente mas com um limite mais alto para o tamanho do arquivo (ou até mesmo sem limite).

O que você acha, @robertatakenaka ?
