### ISSUE TITLE
[FASE 4] Possibilitar a conexão do XC com outros SGBDs por meio de uma ferramenta que facilite isto

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/prodtools#5]
### Descrição da tarefa

Espera-se que o programa prodtools/xc faça o uso de uma ferramenta que abstraia a conexão com bases de dados SQL. É importante que o programa possa operar em um SGBD como o `PosgtreSQL`.

### Subtarefas

- [ ] Verificar a possibilidade de uso do `SQLAlchemy`;
- [ ] Disponibilizar proposta de solução;
- [ ] Implementar solução.

## Considerações e notas
N/A

**Comment by patymori** [comment]
### Proposta de solução

Como as interações com o banco de dados PID Manager estão encapsuladas pelas classes do 
módulo `prodtools/db/pid_versions.py`, seria possível fazer as alterações sem grandes 
impactos no restante da aplicação.
Para o XC, seria possível implementar usando a estratégia do SQLAlchemy ORM, usando Declarative Mapping e Session.
- Cria-se classe mapeada para a tabela `pid_versions`
- Altera-se as classes `PIDVersionsManager` e `PIDVersionsDB`para gerenciar as execuções em 
    session e a conexão com o banco

No arquivo de configuração `<collection>.xc.ini`, a variável `PID_MANAGER` continuará 
recebendo o endereço do banco de dados de acordo com a base de dados a ser usada:
- `postgresql+psycopg2://user:password@hostname:port/database_name` para Postgres
- `sqlite:////path/para/database_name.db` para SQLite

**Comment by jamilatta** [comment]
@patymori 

Entendo que a proposta é utilizamos o SQLAlchemy nos possibilitando conectar tanto no SQlite quanto no Postgres ou outro SQL SGDB? 

Se for isso de acordo!
